version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-db:/var/lib/mysql

  server:
    build: .
    container_name: server
    ports:
      - '8000:8000'
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

volumes:
  mysql-db:
